image:
    repository: smartcitiesdata/mock-cve-data
    tag: latest
    pullPolicy: Always

replicaCount: 1

resources:
    limits:
        memory: 512Mi
        cpu: '1'
    requests:
        memory: 512Mi
        cpu: '1'

service:
    name: mock-cve-data
    port: 80
    targetPort: 3000

crashOnTimer: false
crashOnTimerInterval: 5 # minutes
