image:
    repository: smartcitiesdata/mock-cve-data
    tag: latest
    pullPolicy: Always

replicaCount: 1

resources:
    limits:
        memory: 512Mi
        cpu: '1'
    requests:
        memory: 512Mi
        cpu: '1'

service:
    name: mock-cve-data
    port: 80
    targetPort: 3000

crashOnTimer: false
# Must be at least 12 seconds (12000) for a crash to be detected
#   Since we currently ingest every 10
crashOnTimerInterval: 30000
