image:
    repository: smartcitiesdata/mock-cve-data
    tag: latest
    pullPolicy: IfNotPresent

replicaCount: 1

resources:
    limits:
        memory: 400M
        cpu: 400m
    requests:
        memory: 400M
        cpu: 400m

service:
    name: mock-cve-data
    port: 80
    targetPort: 3000

crashOnTimer: true
crashOnTimerInterval: 10 # minutes
